# Generated by Django 5.1.4 on 2026-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. 6:00 AM - 9:00 PM', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='markets/')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='markets_mar_city_30ce57_idx'), models.Index(fields=['name'], name='markets_mar_name_906f94_idx')],
            },
        ),
    ]
