# Generated by Django 5.1.4 on 2026-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used when no file uploaded)'),
        ),
    ]
