# Generated by Django 5.1.4 on 2026-06-05 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pricing', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='pricelisting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='pricelisting',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'date'], name='pricing_pri_product_1f459a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('vendor', 'product', 'date')},
        ),
        migrations.AddIndex(
            model_name='pricelisting',
            index=models.Index(fields=['product', 'is_active'], name='pricing_pri_product_051632_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelisting',
            index=models.Index(fields=['vendor', 'date'], name='pricing_pri_vendor__472441_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelisting',
            index=models.Index(fields=['date'], name='pricing_pri_date_235a15_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricelisting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vendor', 'product', 'date'), name='uniq_vendor_product_per_day'),
        ),
    ]
