# Generated by Django 5.1.4 on 2026-06-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shop_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendors/')),
                ('is_verified', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='markets.market')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shop_name'],
                'indexes': [models.Index(fields=['is_verified'], name='vendors_ven_is_veri_701f38_idx'), models.Index(fields=['market'], name='vendors_ven_market__b4a7ab_idx')],
            },
        ),
    ]
