# Generated by Django 5.1.4 on 2026-06-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image_url_product_image_url_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image_url',
            field=models.URLField(blank=True, help_text='Shop banner URL (used when no file uploaded)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Main goods this shop sells', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='catalog.category'),
        ),
    ]
